name: 📄 Document Template Request
description: Request a new document template or modification to existing templates
title: "[TEMPLATE] "
labels: ["template", "documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting a new document template! DocForge-ai uses customizable templates to generate different types of documentation.

  - type: textarea
    id: template-name
    attributes:
      label: 📝 Template Name
      description: What should this template be called?
      placeholder: e.g., "API Documentation", "User Manual", "Technical Specification"
    validations:
      required: true

  - type: textarea
    id: template-description
    attributes:
      label: 📋 Template Description
      description: Describe what this template should generate and its purpose
      placeholder: This template should generate comprehensive API documentation including endpoints, parameters, responses, and examples...
    validations:
      required: true

  - type: dropdown
    id: template-type
    attributes:
      label: 📂 Template Type
      description: What type of template is this?
      options:
        - New Template - A completely new document type
        - Modification - Modify an existing template
        - Alternative - Alternative version of existing template
        - Specialized - Specialized version for specific use case
    validations:
      required: true

  - type: textarea
    id: existing-template
    attributes:
      label: 🔄 Existing Template (if applicable)
      description: If modifying an existing template, which one?
      placeholder: e.g., "SRS template", "Architecture template"
      conditional:
        field: template-type
        equals: Modification

  - type: textarea
    id: template-structure
    attributes:
      label: 🏗️ Template Structure
      description: Describe the structure and sections this template should include
      placeholder: |
        The template should include:
        1. Executive Summary
        2. Overview
        3. Detailed Sections
        4. Examples
        5. References
    validations:
      required: true

  - type: textarea
    id: template-content
    attributes:
      label: 📄 Template Content
      description: Provide the markdown template content or a detailed outline
      placeholder: |
        # {project_name} - {template_name}
        
        ## Executive Summary
        {executive_summary}
        
        ## Overview
        {overview}
        
        ## Detailed Sections
        {detailed_sections}
        
        ## Examples
        {examples}
        
        ## References
        {references}
      render: markdown

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 Use Cases
      description: What specific use cases would benefit from this template?
      placeholder: This template would be useful for projects involving...

  - type: textarea
    id: examples
    attributes:
      label: 📚 Examples
      description: Provide examples of the type of content this template should generate
      placeholder: Here's an example of the kind of document this template should create...

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      description: How important is this template to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Urgent - Critical for current project
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Additional Context
      description: Any additional information about this template request
      placeholder: Any other details, references, or context that would be helpful...